language: python
dist: xenial
python:
    - "3.6"
    - "3.7"

before_install:
  - sudo apt-get install gfortran
  - pip install Sphinx sphinx_bootstrap_theme sphinx-autodoc-typehints m2r cffi

install:
  - sphinx-build docs/sphinx build/html
  - touch build/html/.nojekyll # https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/
  - cd tests/js && npm install
  - cd $TRAVIS_BUILD_DIR

script:
  # See https://stackoverflow.com/a/34140498 for why "python -m" is needed.
  - python -m pytest -v -s
  - cd tests/js && npm test
  - cd $TRAVIS_BUILD_DIR

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: build/html
 on:
   branch: master
   condition: $TRAVIS_PYTHON_VERSION == 3.6