dist: xenial

jobs:
  include:
    - language: python
      python: 3.7
      env:
        - VECTORIZE=no
      addons:
        apt:
          packages:
            - gfortran

    - language: python
      python: 3.7
      env:
        - VECTORIZE=numpy
      addons:
        apt:
          packages:
            - gfortran

    - language: python
      python: 3.7
      env:
        - VECTORIZE=numba
      addons:
        apt:
          packages:
            - gfortran

    - language: minimal
      addons:
        snaps:
          - dotnet-sdk --classic
      env:
        - CSHARP=yes

    - language: r

before_install:
  - | 
    set -x
    if [[ "$TRAVIS_PYTHON_VERSION" ]]; then
      pip install cffi # This is common for all
      if [[ "$VECTORIZE" == "no" ]]; then
        pip install Sphinx==2.4.* sphinx_bootstrap_theme sphinx-autodoc-typehints m2r
        pip uninstall -y numpy
      fi
      if [[ "$VECTORIZE" == "numpy" ]]; then
        echo "Do nothing. Numpy is already installed"
      fi
      if [[ "$VECTORIZE" == "numba" ]]; then
        pip install numba
      fi
    fi
    if [[ "$TRAVIS_R_VERSION" ]]; then
      Rscript -e 'install.packages("devtools")'
      cd "$TRAVIS_BUILD_DIR/src/r" || exit
      Rscript tools/deploy.R
    fi
install:
  - | 
    set -x
    if [[ "$TRAVIS_PYTHON_VERSION" ]]; then
      sphinx-build docs/sphinx build/html
      touch build/html/.nojekyll # https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/
      cd tests/js && npm install
      cd $TRAVIS_BUILD_DIR
    fi
script:
  - | 
    set -x
    if [[ "$TRAVIS_PYTHON_VERSION" ]]; then
      cd $TRAVIS_BUILD_DIR
      # See https://stackoverflow.com/a/34140498 for why "python -m" is needed.
      python3 -m pytest -v -s
      # Javascript tests
      cd tests/js && npm test
    if [[ "$TRAVIS_R_VERSION" ]]; then
      R CMD build .
      R CMD check --as-cran psychrolib*tar.gz
    fi
    if [[ "$CSHARP" ]]; then
      cd $TRAVIS_BUILD_DIR
      cd src/c_sharp && dotnet-sdk.dotnet test
    fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/html
  on:
    branch: master
    condition: $VECTORIZE == "no"